<?php

/**
 * Implements hook_theme().
 */
function motaded_custom_theme() {
  return [
    'banner_block' => [
      'variables' => [
        'content' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_page_attachments()
 */
function motaded_custom_page_attachments(array &$attachments) {
  // Check if we are on node edit form.
  if (in_array(\Drupal::routeMatch()->getRouteName(), ['entity.node.edit_form', 'node.add'])) {
    $attachments['#attached']['library'][] = 'motaded_custom/gin-custom';
  }
}


