<?php

/**
 * @file
 * Install, update and uninstall functions for the Metatag Webform module.
 */

/**
 * Implements hook_uninstall().
 */
function metatag_webform_uninstall($is_syncing): void {
  /** @var \Drupal\Core\Config\Entity\ConfigEntityStorage $metatag_defaults_storage */
  $metatag_defaults_storage = \Drupal::entityTypeManager()->getStorage('metatag_defaults');

  foreach ($metatag_defaults_storage->loadMultiple() as $id => $metatag_defaults) {
    if (str_starts_with($id, 'webform.')) {
      $metatag_defaults->delete();
    }
  }
}
