<?php

$color_schemes=[
    'default' => [
      'title' => t('Default'),
      'colors' => [
      'Primary Color' => '#331391',
      'Secondary Color' => '#fd4c66',
      ],
    ],
    'set_1' => [
      'title' => t('Color Set 1'),
      'colors' => [
      'Primary Color' =>'#014b5f',
      'Secondary Color' => '#d2a679',
      ],
    ],
    'set_2' => [
      'title' => t('Color Set 2'),
      'colors' => [
      'Primary Color' => '#153156',
      'Secondary Color' => '#44bcc5',
      ],
    ],
    'set_3' => [
      'title' => t('Color Set 3'),
      'colors' => [
      'Primary Color' => '#949398ff',
      'Secondary Color' => '#f4df4eff',
      ],
    ],
    'set_4' => [
      'title' => t('Color Set 4'),
      'colors' => [
      'Primary Color' => '#153156',
      'Secondary Color' => '#d315a3', 
      ],
    ],
    'set_5' => [
      'title' => t('Color Set 5'),
      'colors' => [
      'Primary Color' => '#2c5f2d',
      'Secondary Color' => '#97bc62ff',
      ],
    ],
    'set_6' => [
      'title' => t('Color Set 6'),
      'colors' => [
      'Primary Color' => '#041b45',
      'Secondary Color' => '#c98723',
      ],
    ],
    'set_7' => [
      'title' => t('Color Set 7'),
      'colors' => [
      'Primary Color' => '#e7e8d1',
      'Secondary Color' => '#b85042',
      ],
    ],
    'set_8' => [
      'title' => t('Color Set 8'),
      'colors' => [
      'Primary Color' => '#014b5f',
      'Secondary Color' => '#fB6a4f',
      ],
    ],
    'set_9' => [
      'title' => t('Color Set 9'),
      'colors' => [
      'Primary Color' => '#ede6b9',
      'Secondary Color' => '#829079',
      ],
    ],
];