<?php

/**
 * @file
 * Functions to support theming in the SASS Starterkit subtheme.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\file\Entity\File;
use Drupal\Core\Entity\EntityInterface;
use Drupal\node\Entity\Node;

/**
 * Implements hook_preprocess_html() for settings form.
 *
 * Replace Barrio setting options with subtheme ones.
 *
 * Example on how to alter theme settings form
*/
function event_pro_preprocess_html(&$variables) {
  
  $variables['time'] = \Drupal::time()->getCurrentTime();
  global $base_url;
  $variables['base_url'] = $base_url;
  $variables['default_color'] = theme_get_setting('default_color');
  $variables['primary_color'] = theme_get_setting('primary_color');
  $variables['secondary_color'] = theme_get_setting('secondary_color');
  // $variables['primary_colors'] = explode(',', theme_get_setting('primary_colors'));
  // $variables['secondary_colors'] = explode(',', theme_get_setting('secondary_colors'));
  $variables['sticky'] = theme_get_setting('sticky');
  $variables['show_pannel'] = theme_get_setting('show_pannel');
  $variables['styles'] = theme_get_setting('styles');
  // header
  $variables['header_variation'] = theme_get_setting('header_variation');
  $variables['color_set'] = ['set_1' => [
      'title' => t('color_set_1'),
      'name' => t('Combo 1'),
      'colors' => [
        'primary_color' => '#331391',
        'secondary_color' => '#fd4c66',
      ],
    ],
    'set_2' => [
      'title' => t('color_set_2'),
      'name' => t('Combo 2'),
      'colors' => [
      'primary_color' => '#014b5f',
      'secondary_color' => '#d2a679',
      ],
    ],
    'set_3' => [
      'title' => t('color_set_3'),
      'name' => t('Combo 3'),
      'colors' => [
      'primary_color' => '#153156',
      'secondary_color' => '#44bcc5',
      ],
    ],
    'set_4' => [
      'title' => t('color_set_4'),
      'name' => t('Combo 4'),
      'colors' => [
      'primary_color' => '#949398ff',
      'secondary_color' => '#f4df4eff',
      ],
    ],
    'set_5' => [
      'title' => t('color_set_5'),
      'name' => t('Combo 5'),
      'colors' => [
      'primary_color' => '#153156',
      'secondary_color' => '#d315a3', 
      ],
    ],
    'set_6' => [
      'title' => t('color_set_6'),
      'name' => t('Combo 6'),
      'colors' => [
      'primary_color' => '#2c5f2d',
      'secondary_color' => '#97bc62ff',
      ],
    ],
    'set_7' => [
      'title' => t('color_set_7'),
      'name' => t('Combo 7'),
      'colors' => [
      'primary_color' => '#041b45',
      'secondary_color' => '#c98723',
      ],
    ],
    'set_8' => [
      'title' => t('color_set_8'),
      'name' => t('Combo 8'),
      'colors' => [
      'primary_color' => '#e7e8d1',
      'secondary_color' => '#b85042',
      ],
    ],
    'set_9' => [
      'title' => t('color_set_9'),
      'name' => t('Combo 9'),
      'colors' => [
      'primary_color' => '#014b5f',
      'secondary_color' => '#fB6a4f',
      ],
    ],
    'set_10' => [
      'title' => t('color_set_10'),
      'name' => t('Combo 10'),
      'colors' => [
      'primary_color' => '#ede6b9',
      'secondary_color' => '#829079',
      ],
    ],
  ];
}


/**
 * Implements hook_preprocess_page() for settings form.
 *
 * Replace Barrio setting options with subtheme ones.
 *
 */
function event_pro_preprocess_page(&$variables) {
//Setting Pannel 
$variables['header_variation'] = theme_get_setting('header_variation');
$variables['show_pannel'] = theme_get_setting('show_pannel');
$variables['sticky'] = theme_get_setting('sticky');
$variables['loader'] = theme_get_setting('loader');
$variables['scroll_top'] = theme_get_setting('scroll_top');
$variables['styles'] = theme_get_setting('styles');
//Hamburger
  $variables['about_title'] = theme_get_setting('about_title');
  $variables['about_site'] = theme_get_setting('about_site');
  $variables['contact_title'] = theme_get_setting('contact_title');
//General Site Details
  $variables['contact_info_title'] = theme_get_setting('contact_info_title'); 
  $variables['address'] = theme_get_setting('address');
  $variables['contact_number'] = theme_get_setting('contact_number');
  $variables['mail_id'] = theme_get_setting('mail_id');
// CopyRight
  $variables['copyright_detail'] = theme_get_setting('copyright_detail')['value'];
//Menu Button
  $variables['button_text'] = theme_get_setting('button_text');
  $variables['button_title'] = theme_get_setting('button_title');
  $variables['button_link'] = theme_get_setting('button_link');
//Page Banner 
  $path = "";
  if (!empty(theme_get_setting('banner_bg'))) {
    $fid = theme_get_setting('banner_bg')[0];
    if (!empty($fid)) {
    $file =File::load($fid);
    $path = Drupal::service('file_url_generator')->generateAbsoluteString($file->getFileUri());
    }
  }
  $variables['banner_bg'] = $path;
//Search Banner Title
  $variables['search_banner_title'] = theme_get_setting('search_banner_title');
}
/**
 * Implements hook_pro_preprocess_form() for settings form.
 *
 * Replace Barrio setting options with subtheme ones.
 *
 */
function event_pro_preprocess_form(&$variables) {
    global $base_url;
    $variables['base_url'] = $base_url;
  }
  
  function event_pro_preprocess_comment(&$variables) {
    global $base_url;
    $variables['base_url'] = $base_url;
  }
/**
 * Implements hook_preprocess_links__language_block() for settings form.
 *
 * Replace Barrio setting options with subtheme ones.
 *
 */
function event_pro_preprocess_links__language_block(&$variables) {
$currentLanguageCode = \Drupal::languageManager()
    ->getCurrentLanguage()
    ->getId();
// replace key of active language with 'activeLink'
foreach ($variables['links'] as $i => $link) {
    /** @var \Drupal\language\Entity\ConfigurableLanguage $linkLanguage */
    $linkLanguage = $link['link']['#options']['language'];
    if ($currentLanguageCode == $linkLanguage->get('id')) {
    $variables['links']['activeLink'] = $link;
    unset($variables['links'][$i]);
    }
}
// if there is only 2 languages remove active one
if (sizeof($variables['links']) == 2) {
    unset($variables['links']['activeLink']);
    // give class 'btn btn-primary' to alternate language
    /** @var \Drupal\Core\Url $alternate */
    $alternate = current($variables['links']);
    $variables['links'] = [$alternate];
}
}

// function event_pro_preprocess_paragraph(&$variables){
//   $paragraph = $variables['paragraph'];

//   if($paragraph->bundle() == 'schedules'){
//     dpm(array_keys($variables['content']['field_people'][0]));
//   }
// }  
/**
 * Implements hook_preprocess_node() for settings form.
 *
 * Replace Barrio setting options with subtheme ones.
 *
 */
function event_pro_preprocess_node(&$variables){
  //Next Prev
    // Pager
    if ($variables['node']->getType() == 'blog'){
      $nids = \Drupal::entityQuery('node')->accessCheck(FALSE)
                ->condition('type','blog')->condition('status',1)->execute();
      $blog_nodes = [];
      foreach($nids as $n){
        $blog_nodes[] = $n;
      }
  
      $nid = $variables['node']->id();
      $key = array_search($nid, $blog_nodes);
  
      // Next node url
      if($nid == end($blog_nodes)){
        $data_next = Node::load($blog_nodes[0]);
      }else{
        $data_next = Node::load($blog_nodes[$key+1]);
      }
  
      // Prev node url
      if($nid == $blog_nodes[0]){
        $lkey = array_search(end($blog_nodes), $blog_nodes);
        $data_prev = Node::load($blog_nodes[$lkey]);
      }
      else{
        $data_prev = Node::load($blog_nodes[$key-1]);
      }
      $variables['next_url'] = $data_next->toUrl()->setAbsolute()->toString();
      $variables['prev_url'] = $data_prev->toUrl()->setAbsolute()->toString();
      $variables['prev_label'] = $data_prev->get("title")->value;
      $variables['next_label'] = $data_next->get("title")->value;
    }
    // Add to any module
    $block = \Drupal\block\Entity\Block::load('addtoanybuttons');
    $variables['share'] = \Drupal::entityTypeManager()
      ->getViewBuilder('block')
      ->view($block);

    // Blog Comments
    if ($variables['node']->getType() == 'blog') {
      $variables['comment_count'] = $variables['node']->get('field_comments')->comment_count;
    }
    // Taxonamy viewmode
    if ($variables['node']->getType() == 'team') {
      $view_mode = $variables['view_mode'];
      print_r(view_mode);
    }
}
//<=========LOGIN PAGE===============>/
function event_pro_preprocess_user_login(&$variables) {
  $variables['login_banner_title'] = theme_get_setting('login_banner_title');
  $variables['login_title'] = theme_get_setting('login_title');
  $variables['login_name_description'] = theme_get_setting('login_name_description');
  $variables['login_password_description'] = theme_get_setting('login_password_description');
  //Page Banner 
  $path = "";
  if (!empty(theme_get_setting('banner_bg'))) {
    $fid = theme_get_setting('banner_bg')[0];
    if (!empty($fid)) {
    $file =File::load($fid);
    $path = Drupal::service('file_url_generator')->generateAbsoluteString($file->getFileUri());
    }
  }
  $variables['banner_bg'] = $path;
}
//<=========REGISTER PAGE===============>/
function event_pro_preprocess_user_register(&$variables) {
  $variables['register_banner_title'] = theme_get_setting('register_banner_title');
  $variables['register_title'] = theme_get_setting('register_title');
  $variables['register_name_description'] = theme_get_setting('register_name_description');
  $variables['register_mail_description'] = theme_get_setting('register_mail_description');
  //Page Banner 
  $path = "";
  if (!empty(theme_get_setting('banner_bg'))) {
    $fid = theme_get_setting('banner_bg')[0];
    if (!empty($fid)) {
    $file =File::load($fid);
    $path = Drupal::service('file_url_generator')->generateAbsoluteString($file->getFileUri());
    }
  }
  $variables['banner_bg'] = $path;
}
//<=========RESET PASSWORD PAGE===============>//
function event_pro_preprocess_user_pass(&$variables) {
  $variables['reset_banner_title'] = theme_get_setting('reset_banner_title');
  $variables['reset_page_title'] = theme_get_setting('reset_page_title');
  $variables['reset_pass_name_description'] = theme_get_setting('reset_pass_name_description');
  //Page Banner 
  $path = "";
  if (!empty(theme_get_setting('banner_bg'))) {
    $fid = theme_get_setting('banner_bg')[0];
    if (!empty($fid)) {
    $file =File::load($fid);
    $path = Drupal::service('file_url_generator')->generateAbsoluteString($file->getFileUri());
    }
  }
  $variables['banner_bg'] = $path;
}
//--------------FORM ALTER----------------->
function event_pro_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if($form_id == 'user_login_form'){
    $form['name']['#placeholder']= 'Enter your Name';
    $form['pass']['#placeholder'] = t('Enter your Password');
  }

  if($form_id == 'user_register_form'){
    $form['account']['mail']['#placeholder']= 'Enter your email';
    $form['account']['name']['#placeholder']= 'Enter your name';
    $form['actions']['submit']['#value'] = t('Register');  
  }

  if($form_id == 'user_pass'){
    $form['name']['#attributes']['placeholder']= 'Enter your name or email';
    $form['actions']['submit']['#value'] = t('Reset');  
  }
}

function event_pro_theme(&$existing, $type, $theme, $path) {
  $hooks = array();
  $hooks['user_login_form'] = array(
   'render element' => 'form',
   'template' => 'user-login-form',
   'preprocess functions' => array(
      'event_pro_preprocess_user_login'
   ),
  );
  $hooks['user_register_form'] = array(
   'render element' => 'form',
   'template' => 'user-register-form',
   'preprocess functions' => array(
      'event_pro_preprocess_user_register'
   ),
  );
  $hooks['user_pass'] = array(
   'render element' => 'form',
   'template' => 'user-pass-form',
   'preprocess functions' => array(
      'event_pro_preprocess_user_pass'
   ),
  );
  return $hooks;  
}
//<============Maintenance Page===========>
function event_pro_preprocess_maintenance_page(&$variables) {
  $variables['mode_type'] = theme_get_setting('mode_type');
  //Maintenance
  $variables['maintenance_mode_title'] = theme_get_setting('maintenance_mode_title');
  $variables['maintenance_mode_description'] = theme_get_setting('maintenance_mode_description'); 
    //Background Image
    $path = "";
    if (!empty(theme_get_setting('bg_image_m'))) {
      $fid = theme_get_setting('bg_image_m')[0];
      if (!empty($fid)) {
      $file =File::load($fid);
      $path = Drupal::service('file_url_generator')->generateAbsoluteString($file->getFileUri());
      }
    }
    $variables['bg_image_m'] = $path;
  //Coming Soon
  $variables['coming_soon_title'] = theme_get_setting('coming_soon_title');
  $variables['coming_soon_description'] = theme_get_setting('coming_soon_description');
    //Background Image
    $path = "";
    if (!empty(theme_get_setting('bg_image_c'))) {
      $fid = theme_get_setting('bg_image_c')[0];
      if (!empty($fid)) {
      $file =File::load($fid);
      $path = Drupal::service('file_url_generator')->generateAbsoluteString($file->getFileUri());
      }
    }
    $variables['bg_image_c'] = $path;
    $variables['launch_date'] = theme_get_setting('launch_date');
  $variables['#attached'] = [
      'drupalSettings' => [
          'custom_date' => $variables['custom_date'] = theme_get_setting('launch_date'),
      ],
  ];

}

/**
 * Searh Result Page.
 **
 */
function event_pro_preprocess_item_list__search_results(&$variables) {
  global $base_url;
  $variables['base_url'] = $base_url;
  // Search Result count
  $pager = \Drupal::service('pager.manager')->getPager();
  if (!empty($pager)){
    $count_results = $pager->getTotalItems();
    $variables['total_items_count'] = $count_results;
  }
  else{
    $variables['total_items_count'] = 0;
  }
  // Search Keyword
  $current_path = \Drupal::request()->getpathInfo();
  //echo $current_path;
  if ($current_path == '/search/node') {
    if (\Drupal::request()->query->has('keys')) {
      $keywords = \Drupal::request()->query->get('keys');
      $variables['keyword'] = $keywords;
    }
  }
}

function event_pro_preprocess_paragraph__media_content(&$vars) {         
    $vars['delta'] = NULL;
  foreach ($vars['paragraph']->getParentEntity()->field_media_content->getValue() as $delta => $item) {
    if ($item['target_id'] === $vars['paragraph']->id()) {
      $vars['delta'] = $delta;
      break;
    }
  }
}

function event_pro_preprocess_paragraph__faq(&$vars) {         
  $vars['delta'] = NULL;
  foreach ($vars['paragraph']->getParentEntity()->field_faq->getValue() as $delta => $item) {
    if ($item['target_id'] === $vars['paragraph']->id()) {
      $vars['delta'] = $delta;
      break;
    }
  }
}

function event_pro_library_info_alter(&$libraries, $ext){
  unset($libraries['form']);
}