<?php
use Drupal\Core\Language\LanguageInterface;
use Drupal\node\Entity\Node;
/**
 * Implements hook_preprocess_HOOK() for block templates.
 *
 * Preprocesses variables for the block template.
 * Adds block id as variable.
 */
function motaded_theme_preprocess_block(array &$variables) {
  if (!empty($variables['elements']['#id']) && $variables['elements']['#id'] == 'motaded_theme_mainnavigation') {
    $variables['content']['#attributes']['data-block-id'] = $variables['elements']['#id'];
  }
}

function motaded_theme_theme_suggestions_menu_alter(array &$suggestions, array $variables) {
  if (isset($variables['attributes']['data-block-id'])) {
    $block = \Drupal\block\Entity\Block::load($variables['attributes']['data-block-id']);
    if ($block) {
      array_push($suggestions, 'menu__' . str_replace('-', '_', $block->getRegion()));
    }
  }
}

/**
 * Implements hook_preprocess_HOOK() for page templates.
 *
 * Preprocesses variables for the page template.
 * Adds default logo path variable.
 */
function motaded_theme_preprocess_page(&$variables) {
  // Adds logo path to page.html.twig variables.
  $variables['logo_path'] = \Drupal::service('file_url_generator')->generateString(theme_get_setting('logo.url'));
}

/**
 * Implements hook_preprocess_HOOK() for node templates.
 *
 * Preprocesses variables for the node template.
 * Adds body summary variable
 */
function motaded_theme_preprocess_node(&$variables) {
  $node = $variables['node'];
  if ($node->hasField('body') && !$node->get('body')->isEmpty()) {
    $variables['summary'] = ['#markup' => $variables['node']->body->summary];
  }

  // Add step numbers to field_steps_to_obtain items.
  if ($node->bundle() == 'page' && !empty($variables['content']['field_steps_to_obtain'])) {
    foreach ($variables['content']['field_steps_to_obtain'] as $i => &$item) {
      if (is_numeric($i)) {
        $item['#number'] = $i;
      }
    }
  }
}

/**
 * Implements hook_theme_suggestions_page_alter().
 */
function motaded_theme_theme_suggestions_page_alter(array &$suggestions, array $variables) {
  if ($node = \Drupal::routeMatch()->getParameter('node')) {
    $suggestions[] = 'page__' . $node->bundle();
  }
}

/**
 * Implements hook_preprocess_paragraph__steps().
 */
function motaded_theme_preprocess_paragraph__steps(array &$variables) {
  /** @var \Drupal\paragraphs\Entity\Paragraph $paragraph */
  $paragraph = $variables['paragraph'];
  $steps = [];
  $langcode = \Drupal::languageManager()->getCurrentLanguage(LanguageInterface::TYPE_CONTENT)->getId();

  // Check if field_paragraphs exists and has data.
  if ($paragraph->hasField('field_paragraphs') && !$paragraph->get('field_paragraphs')->isEmpty()) {
    foreach ($paragraph->get('field_paragraphs')->referencedEntities() as $item) {
      // Try to get the translation if available.
      if ($item->hasTranslation($langcode)) {
        $item = $item->getTranslation($langcode);
      }
      // Each $item is a sub-paragraph, e.g., a single step/card.
      $stepTitle = $item->hasField('field_sub_title') ? $item->get('field_sub_title')->value : '';
      $title = $item->hasField('field_title') ? $item->get('field_title')->value : '';
      $desc = $item->hasField('field_body') ? $item->get('field_body')->processed : '';
      $img_url = '';
      if ($item->hasField('field_media') && !$item->get('field_media')->isEmpty()) {
        /** @var \Drupal\media\Entity\Media $media */
        $media = $item->get('field_media')->entity;
        if ($media && $media->hasField('field_media_image') && !$media->get('field_media_image')->isEmpty()) {
          $file = $media->get('field_media_image')->entity?->uri?->value;
          $img_url = $file ? \Drupal::service('file_url_generator')->generateAbsoluteString($file) : NULL;
        }
      }

      $steps[] = [
        'step_title' => $stepTitle,
        'title' => $title,
        'desc'  => $desc,
        'img'   => $img_url,
      ];
    }
  }

  // Attach the structured data to drupalSettings.
  // Use paragraph ID so multiple 'steps' paragraphs don’t overwrite each other.
  $variables['#attached']['drupalSettings']['motaded_theme']['steps'] = $steps;

  // Attach JS library.
  $variables['#attached']['library'][] = 'motaded_theme/steps';
}

/**
 * Preprocess for News View block (unformatted).
 */
function motaded_theme_preprocess_views_view_unformatted__news__block_4(&$variables) {
  $langcode = \Drupal::languageManager()->getCurrentLanguage(LanguageInterface::TYPE_CONTENT)->getId();
  foreach ($variables['rows'] as &$row) {
    $entity = $row['content']['#row']->_entity ?? NULL;
    // Try to get the translation if available.
    if ($entity->hasTranslation($langcode)) {
      $entity = $entity->getTranslation($langcode);
    }

    if ($entity && $entity->hasField('field_media') && !$entity->get('field_media')->isEmpty()) {
      $media = $entity->get('field_media')->entity;
      if ($media && $media->hasField('field_media_image') && !$media->get('field_media_image')->isEmpty()) {
        $file = $media->get('field_media_image')->entity?->uri?->value;
        $img_alt = $media->get('field_media_image')->entity?->alt;
        $img_url = $file ? \Drupal::service('file_url_generator')->generateAbsoluteString($file) : NULL;
      }
    }

    // Add title, URL, and created date.
    $row['title'] = $entity->label();
    $row['url'] = $entity->toUrl()->toString();
    $row['image']['url'] = $img_url ?? '';
    $row['image']['alt'] = $img_alt ?? '';
    $row['created'] = $entity->getCreatedTime() ? \Drupal::service('date.formatter')->format($entity->getCreatedTime(), 'custom', 'Y-m-d') : '';
  }
}
/**
 * Preprocess for News View block (unformatted).
 */
function motaded_theme_preprocess_views_view_unformatted__partners__block_2(&$variables) {
  foreach ($variables['rows'] as &$row) {
    $entity = $row['content']['#row']->_entity ?? NULL;

    if ($entity && $entity->hasField('field_media') && !$entity->get('field_media')->isEmpty()) {
      $media = $entity->get('field_media')->entity;
      if ($media && $media->hasField('field_media_image') && !$media->get('field_media_image')->isEmpty()) {
        $file = $media->get('field_media_image')->entity?->uri?->value;
        $img_alt = $media->get('field_media_image')->entity?->alt;
        $img_url = $file ? \Drupal::service('file_url_generator')->generateAbsoluteString($file) : NULL;
      }
    }

    $row['image']['url'] = $img_url ?? '';
    $row['image']['alt'] = $img_alt ?? '';
  }
}

/**
 * Implements hook__preprocess_HOOK().
 */
function motaded_theme_preprocess_breadcrumb(&$variables) {
  $node = \Drupal::routeMatch()->getParameter('node');
  if ($node) {
    $prefix = getLanguagePrefix();
    $prefix = str_ends_with($prefix, "/") ? $prefix : $prefix . "/";
    
    if (isset($variables['breadcrumb'][1]) && in_array($variables['breadcrumb'][1]['url'], ['/node', '/ar/node', '/beta/node', '/beta/ar/node'])) {
      array_splice($variables['breadcrumb'], 1, 1);
    }

    if ($node->bundle() == "article") {
      if (isset($variables['breadcrumb'][1]) && $variables['breadcrumb'][1]['url'] != '/blog') {
        $list_crumb = [
          'text' => t('Articles'),
          'url' => $prefix . "blog",
        ];
        array_splice($variables['breadcrumb'], 1, 0, [$list_crumb]);
      }
    } elseif ($node->bundle() == "page") {
      if (isset($variables['breadcrumb'][1]) && $variables['breadcrumb'][1]['url'] != '/services') {
        $list_crumb = [
          'text' => t('Services'),
          'url' => $prefix . "services",
        ];
        array_splice($variables['breadcrumb'], 1, 0, [$list_crumb]);
      }
    } elseif ($node->bundle() == "news") {
      if (isset($variables['breadcrumb'][1]) && $variables['breadcrumb'][1]['url'] != '/news') {
        $list_crumb = [
          'text' => t('News'),
          'url' => $prefix . "news",
        ];
        array_splice($variables['breadcrumb'], 1, 0, [$list_crumb]);
      }
    }
  }
}

/**
 * Helper function to get language prefix.
 */
function getLanguagePrefix() {
  if($prefixes = \Drupal::config('language.negotiation')->get('url.prefixes')) {
    $language = \Drupal::languageManager()->getCurrentLanguage()->getId();
    return "/". $prefixes[$language];
  }
  return null;
}


/**
 * Implements hook_form_FORM_ID_alter().
 */
function motaded_theme_form_views_exposed_form_alter(&$form,  Drupal\Core\Form\FormStateInterface $form_state) {
  if ($form['#id'] == 'views-exposed-form-services-block-2') {
    if (!isset($form['field_taxonomy_target_id'])) {
      return;
    }

    // Remove "All".
    unset($form['field_taxonomy_target_id']['#options']['All']);

    $options = $form['field_taxonomy_target_id']['#options'];
    $first = array_key_first($options);

    $input = $form_state->getUserInput();
    $val = $input['field_taxonomy_target_id'] ?? NULL;

    // Only set first when value missing or "All".
    if ($val === 'All' || empty($val)) {
      $form['field_taxonomy_target_id']['#default_value'] = $first;
      $input['field_taxonomy_target_id'] = $first;
      $form_state->setUserInput($input);
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 * Prefill service field in contact webform based on query parameter.
 */
function motaded_theme_form_alter(&$form,  Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id == "webform_submission_contact_add_form") {
    $nid = \Drupal::request()->request->get('service_id');

    if (!empty($nid) && is_numeric($nid)) {
      $node = Node::load($nid);
      if ($node) {
        $url = $node->toUrl('canonical', ['absolute' => TRUE])->toString();
        $form['elements']['service']['#default_value'] = $url;
      }
    }
  }


}

/**
 *  Block suggestions for custom block bundles.
 */
function motaded_theme_theme_suggestions_block_alter(array &$suggestions, array $variables) {
  if (isset($variables['elements']['content']['#block_content'])) {
    array_splice($suggestions, 1, 0, 'block__bundle__' . $variables['elements']['content']['#block_content']->bundle());
  }
}