<?php

/**
 * @file
 * Devel debug log module install/schema hooks.
 */

/**
 * {@inheritdoc}
 */
function devel_debug_log_schema() {
  $schema = [];

  $schema['devel_debug_log'] = [
    'description' => 'Table for storing debug messages.',
    'fields' => [
      'id' => [
        'description' => 'The message identifier.',
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ],
      'timestamp' => [
        'description' => 'The Unix timestamp when the message was saved.',
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
      ],
      'title' => [
        'description' => 'The title of the debug message.',
        'type' => 'varchar',
        'length' => '255',
        'not null' => TRUE,
        'default' => '',
      ],
      'message' => [
        'description' => 'The debug message.',
        'type' => 'text',
        'size' => 'big',
        'not null' => TRUE,
      ],
      'serialized' => [
        'description' => 'Indicates whether the message is serialized.',
        'type' => 'int',
        'size' => 'small',
        'not null' => TRUE,
        'default' => 0,
      ],
    ],
    'primary key' => ['id'],
  ];

  return $schema;
}
