<?php

/**
 * Implements hook_preprocess_HOOK() for block templates.
 *
 * Preprocesses variables for the block template.
 * Adds block id as variable.
 */
function motaded_theme_preprocess_block(array &$variables) {
  if (!empty($variables['elements']['#id']) && $variables['elements']['#id'] == 'motaded_theme_mainnavigation') {
    $variables['content']['#attributes']['data-block-id'] = $variables['elements']['#id'];
  }
}

function motaded_theme_theme_suggestions_menu_alter(array &$suggestions, array $variables) {
  if (isset($variables['attributes']['data-block-id'])) {
    $block = \Drupal\block\Entity\Block::load($variables['attributes']['data-block-id']);
    if ($block) {
      array_push($suggestions, 'menu__' . str_replace('-', '_', $block->getRegion()));
    }
  }
}

/**
 * Implements hook_preprocess_HOOK() for page templates.
 *
 * Preprocesses variables for the page template.
 * Adds default logo path variable.
 */
function motaded_theme_preprocess_page(&$variables) {
  // Adds logo path to page.html.twig variables.
  $variables['logo_path'] = \Drupal::service('file_url_generator')->generateString(theme_get_setting('logo.url'));
}

/**
 * Implements hook_preprocess_HOOK() for node templates.
 *
 * Preprocesses variables for the node template.
 * Adds body summary variable
 */
function motaded_theme_preprocess_node(&$variables) {
  $node = $variables['node'];
  if ($node->hasField('body') && !$node->get('body')->isEmpty()) {
    $variables['summary'] = ['#markup' => $variables['node']->body->summary];
  }
}