<?php

/**
 * @file
 * Install, update and uninstall hooks for Motaded theme.
 */

/**
 * Make footer about text available for interface translation.
 *
 * This ensures the string is extracted when running:
 * drush locale:check
 * drush locale:update
 */
function motaded_theme_install() {
  t("Motaded Consultancy is a premier firm facilitating Business Setup in Saudi Arabia. We provide expert solutions for company formation, licensing, and seamless market entry within the Kingdom.");
}
